version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase # Connection string for MongoDB
      - JWT_SECRET=your_jwt_secret # Add your JWT secret here
    depends_on:
      - mongo # Ensure MongoDB starts before the app

  mongo:
    image: mongo:latest # Use the latest MongoDB image
    ports:
      - "27017:27017" # Map port 27017 on the host to MongoDB port
    volumes:
      - mongo_data:/data/db # Persist data in a volume

volumes:
  mongo_data: # Define a named volume for MongoDB data persistence